In [1]:
import numpy as np #Libray for creating it'a main object, Arrays + different functions for it
import pandas as pd #Library to transform data, manipulate data
import matplotlib.pyplot as plt #Library for visualizing data
from matplotlib.colors import ListedColormap

from sklearn.model_selection import train_test_split
#model_selection is a class or sub/package.


#test_train_split is where we can pass in a dataset and it will automatically devide it into a training + testing sample.
# it outputs  x_train, x_test, y_train data, y_test ==> As arrays. 

from sklearn.tree import DecisionTreeClassifier
#Here we want to use the Tree, specifically the Decision Tree Classifier algorithm

#Documentation: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html
#Look for parameters of Decision Tree Clasifier



In [2]:
# read Iris data set

#Take the CSV and transform it into a Dataframe --> A table. 
#df = data file
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header = None)
#df = pd.read_csv('iris.csv.xlsx', header = None)
df.tail()

print(df)

#''' Store the data into integer indexed array : all rows : all columns . IA = Indexed Array  '''
IA = df.iloc[:,:].values
for i_ in range(0,len(df),1):
    print(i_, IA[i_,:])


#''' Store only the last column, The iris type. CL == Column Last '''
Cl = IA[:,4] 
print(Cl)

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa


In [3]:
# get Iris classifications

#Find the unique values. Ie, the three types of Iris. IC = Iris Column
IC = np.unique(IA[:,4])
print (IC)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [4]:
pltC = ('red', 'blue', 'green') #Array of Plot Colors
pltM = ('o', 'x', '*') #Array of Plot symbol

#Associate a classification with a color and a symbol
for i in range(0,3):
    print(IC[i], pltC[i], pltM[i])
          

Iris-setosa red o
Iris-versicolor blue x
Iris-virginica green *


In [5]:
# setup Iris feature lablels

#Iris F = Iris Features
IrisF=("sepal length in cm", "sepal width in cm", "petal length in cm", "petal width in cm")
for i in range(0,4):
    print(IrisF[i])




sepal length in cm
sepal width in cm
petal length in cm
petal width in cm


In [6]:
features = IA[:, 0:4]
classificationsLabels = IA[:, 4]
print(features)
print(classificationsLabels)

# Converting labels to numeric values. 
classificationValues = np.zeros(len(classificationsLabels))
#print(classificationValues)

for i in range(0, len(classificationValues)):
    if(classificationsLabels[i] == 'Iris-setosa'):
        classificationValues[i] = 0
    elif(classificationsLabels[i] == 'Iris-versicolor'):
        classificationValues[i] = 1
    elif(classificationsLabels[i] == 'Iris-virginica'):
        classificationValues[i] = 2
print(classificationValues)  

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [7]:
from sklearn.model_selection import train_test_split

X_Train, X_Test, Y_Train, Y_Test = train_test_split(features, classificationValues, test_size=0.50)

In [8]:
# Fit for various depth trees


#We iterate through differnt depths of the tree, starting with depth of 1


entropy_tree = DecisionTreeClassifier(criterion='entropy', random_state = 1)
    #create a decision tree classifier, with the impurity of entropy ( -Sum p(i|t)*log2p(i|t)  )
    #Remember a higher entropy value means that the data is more heterogenous
    #Thus we want a lower entropy value!
    
entropy_tree.fit(X_Train, Y_Train)
    #Build a decision tree classifier from the training set (X, y).
    #Have the tree use the test data, and the above information, ie the impurity measure, and depth,
    #to now train it
    
    

Y_Predict = entropy_tree.predict(X_Test)
#print(Y_Predict)
    

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(Y_Test, Y_Predict))
     
    #Here we go through our model after it has been built, again with the training data first
#print(entropy_tree.score(X_Train,Y_Train))
    # Return the mean accuracy on the given train data and labels  per tree (And the maximum depth it went through)
    
    
    #Now we go through our model using the testing data.
#print(entropy_tree.score(X_Test,Y_Test))
    # Return the mean accuracy on the given test data and labels  per tree (And the maximum depth it went through)
    

Accuracy: 0.9466666666666667


In [9]:
# Fit for various depth trees


gini_tree = DecisionTreeClassifier(random_state = 1)
    #create a decision tree classifier, with the impurity of gini ( 1- Sum p(i|t)^2   )
    #Remember a higher entropy value means that the data is more heterogenous
    #Thus we want a lower entropy value!

gini_tree.fit(X_Train, Y_Train)
    #Build a decision tree classifier from the training set (X, y).
    #Have the tree use the test data, and the above information, ie the impurity measure, and depth,
    #to now train it
    
    
    
     
    #Here we go through our model after it has been built, again with the training data first
#print(gini_tree.score(X_Train,Y_Train))
    # Return the mean accuracy on the given train data and labels  per tree (And the maximum depth it went through)

Y_Predict = gini_tree.predict(X_Test)
#print(Y_Predict)
    

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(Y_Test, Y_Predict))
    
    #Now we go through our model using the testing data.
#print(gini_tree.score(X_Test,Y_Test))
    # Return the mean accuracy on the given test data and labels  per tree (And the maximum depth it went through)
    

Accuracy: 0.9466666666666667


In [ ]:
To summerize my results.


For this assignment, we had to develop decision tree classifiers
for the iris data set using different impurtiy measures.
In other words, how unhomogeous are the sample points
in their space after the decision boundary.

We had to train our models on all 4 features,
sepal length, sepal width, petal lenght, and petal width.
Additionally, we had to include all three classifications,
setosa, versicolor, and virginica. 

We divided the Iris dataset into testing and training data by 0.5,
following with previous assignments. 

The two impurity measures (limited by sckit learing)
are gini impurity and entropy impurity. 

Entropy is the amount of disorder that their is in a tree.
Thus with every boundry made, Entropy seeks to compare the 
number of points that accurately fall within the classification
and those that do not. Because entropy = disorder, a higher entropy 
value means that the data is more homogenous (less of what we want).

Gini is greater if the classes are perfectly mixes, ie for each class
there is a mix of values. (Similar to entropy, but less focus on homogenuity)
Gini impurity seeks to decrease the probability of misclassification. 


==== Start of Informal Math interpretation ====

However, in practice, Entropy + Gini produce very similar results. 
Mathematically, Entropy ~ log2(proportion samples fall in class | total)
and Gini = (proportion samples fall in class | total ) ^ 2 
x ^ 2 = log2(X) With  minor differences to the math ~ about the same.

==== End of Informal Math interpretation ====



As we can see in our results above, both Entropy + Gini  (Impurity measure)
Decision Tree Classifiers for the Iris data set produce exactly the 
same accuracy result of 0.9466666666666667. Which follows that in practice, Gini and Entroy 
provide approximately the same result. 