In [1]:
import numpy as np #Libray for creating it'a main object, Arrays + different functions for it
import pandas as pd #Library to transform data, manipulate data
import matplotlib.pyplot as plt #Library for visualizing data
from matplotlib.colors import ListedColormap






In [2]:
# Just self notes
# Error = 1 - accuracy

In [3]:
# read Iris data set

#Take the CSV and transform it into a Dataframe --> A table. 
#df = data file
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header = None)
#df = pd.read_csv('iris.csv.xlsx', header = None)
df.tail()

print(df)

#''' Store the data into integer indexed array : all rows : all columns . IA = Indexed Array  '''
IA = df.iloc[:,:].values
for i_ in range(0,len(df),1):
    print(i_, IA[i_,:])


#''' Store only the last column, The iris type. CL == Column Last '''
Cl = IA[:,4] 
print(Cl)

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa


In [4]:
# get Iris classifications

#Find the unique values. Ie, the three types of Iris. IC = Iris Column
IC = np.unique(IA[:,4])
print (IC)

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [5]:
pltC = ('red', 'blue', 'green') #Array of Plot Colors
pltM = ('o', 'x', '*') #Array of Plot symbol

#Associate a classification with a color and a symbol
for i in range(0,3):
    print(IC[i], pltC[i], pltM[i])
          

Iris-setosa red o
Iris-versicolor blue x
Iris-virginica green *


In [6]:
# setup Iris feature lablels

#Iris F = Iris Features
IrisF=("sepal length in cm", "sepal width in cm", "petal length in cm", "petal width in cm")
for i in range(0,4):
    print(IrisF[i])



sepal length in cm
sepal width in cm
petal length in cm
petal width in cm


In [7]:
features = IA[:, 0:4]
classificationsLabels = IA[:, 4]
print(features)
print(classificationsLabels)

# Converting labels to numeric values. 
classificationValues = np.zeros(len(classificationsLabels))
print(classificationValues)

for i in range(0, len(classificationValues)):
    if(classificationsLabels[i] == 'Iris-setosa'):
        classificationValues[i] = 0
    elif(classificationsLabels[i] == 'Iris-versicolor'):
        classificationValues[i] = 1
    elif(classificationsLabels[i] == 'Iris-virginica'):
        classificationValues[i] = 2
print(classificationValues)  

[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [8]:
from sklearn import svm

In [9]:
from sklearn.model_selection import train_test_split

X_Train, X_Test, Y_Train, Y_Test = train_test_split(features, classificationValues, test_size=0.50, random_state=0)

In [10]:
linear_clf = svm.SVC(kernel='linear')

In [11]:
linear_clf.fit(X_Train, Y_Train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
#linear_clf.support_vectors_ #The samples (values) that make up the support vector points

In [13]:
# linear_clf.support_ #The indicies of all of the support vectors 

In [14]:
# linear_clf.n_support_ #==> Show the number of support vectors per classificaiton 

In [15]:
linear_training_error = linear_clf.score(X_Train, Y_Train) #Compute the mean accuracy for training data
linear_testing_error = linear_clf.score(X_Test, Y_Test) # Compute the mean accuracy for testing data
print(linear_training_error)
print(linear_testing_error)
      
#Accuracys are pretty similar

0.9733333333333334
0.9733333333333334


In [16]:
# Let's look into the accuracy per classification (Instead of total/overall)
# We will look at the accuracy between the Testing data!

linear_Y_Predict = linear_clf.predict(X_Test)
print(linear_Y_Predict)

[2. 1. 0. 2. 0. 2. 0. 1. 1. 1. 2. 1. 1. 1. 1. 0. 1. 1. 0. 0. 2. 1. 0. 0.
 2. 0. 0. 1. 1. 0. 2. 1. 0. 2. 2. 1. 0. 2. 1. 1. 2. 0. 2. 0. 0. 1. 2. 2.
 1. 2. 1. 2. 1. 1. 2. 2. 2. 2. 1. 2. 1. 0. 2. 1. 1. 1. 1. 2. 0. 0. 2. 1.
 0. 0. 1.]


In [17]:
#Import scikit-learn metrics module for accuracy calculation\n",
from sklearn import metrics

# Confirm score is the same as above for testing data (As it should be)
print("Accuracy:",metrics.accuracy_score(Y_Test, linear_Y_Predict))
# It is. 

Accuracy: 0.9733333333333334


In [18]:
from sklearn.metrics import classification_report
print(classification_report(Y_Test, linear_Y_Predict))

#Focusing on just precision, we can see that setosa is the most correctly classified, then versicolor, then viriginica. 
#With a decrease in precision

#While this model is different from Adeline, remmeber that we had the mos taccuracy there, 
#for setosa becasue it was more defined/seperated by its features. 
#Having lower sepall widht/length sepal values.


             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00        21
        1.0       0.97      0.97      0.97        30
        2.0       0.96      0.96      0.96        24

avg / total       0.97      0.97      0.97        75



In [19]:
# Now we create a polynomial kernal SVM 

In [20]:
polynomial_clf = svm.SVC(kernel='poly')

In [21]:
polynomial_clf.fit(X_Train, Y_Train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [22]:
polynomial_training_accuracy = polynomial_clf.score(X_Train, Y_Train) #Compute the mean accuracy for training data
polynomial_testing_accuracy = polynomial_clf.score(X_Test, Y_Test) # Compute the mean accuracy for testing data
print(polynomial_training_accuracy)
print(polynomial_testing_accuracy)
      
#Accuracy for training data is almost perfect. Accuracy for testing data is approximately the same as linear

1.0
0.9733333333333334


In [23]:
# Let's look into the accuracy per classification (Instead of total/overall)
# We will look at the accuracy between the Testing data!

polynomial_Y_Predict = polynomial_clf.predict(X_Test)
print(polynomial_Y_Predict)

[2. 1. 0. 2. 0. 2. 0. 1. 1. 1. 2. 1. 1. 1. 1. 0. 1. 1. 0. 0. 2. 1. 0. 0.
 2. 0. 0. 1. 1. 0. 2. 1. 0. 2. 2. 1. 0. 2. 1. 1. 2. 0. 2. 0. 0. 1. 2. 2.
 2. 2. 1. 2. 1. 1. 2. 1. 2. 2. 1. 2. 1. 0. 2. 1. 1. 1. 1. 2. 0. 0. 2. 1.
 0. 0. 1.]


In [24]:
#Import scikit-learn metrics module for accuracy calculation\n",
from sklearn import metrics

# Confirm score is the same as above for testing data (As it should be)
print("Accuracy:",metrics.accuracy_score(Y_Test, polynomial_Y_Predict))
# It is. 

Accuracy: 0.9733333333333334


In [25]:
from sklearn.metrics import classification_report
print(classification_report(Y_Test, polynomial_Y_Predict))

#Focusing on just precision, we can see that setosa is the most correctly classified, then versicolor, then viriginica. 
#With a decrease in precision

#While this model is different from Adeline, remmeber that we had the mos taccuracy there, 
#for setosa becasue it was more defined/seperated by its features. 
#Having lower sepall widht/length sepal values.



             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00        21
        1.0       0.97      0.97      0.97        30
        2.0       0.96      0.96      0.96        24

avg / total       0.97      0.97      0.97        75



In [26]:
#Overall, we notice very similar accuracies.
# The only difference here is how the training data was more accuractly fit that in the linear model. 


#Polynomial Kernels however, do allow us to better fit the data (Or a polynomial function) Hence why we notice a 1.0 fit for the training data,
#However our testing data stillis off a bit.

In [27]:
# SVM with Kernal RBF (Good for non-linearly seperable data. It tries to group them however can overfit -- for small data sets.)

In [28]:
rbf_clf = svm.SVC(kernel='rbf')

In [29]:
rbf_clf.fit(X_Train, Y_Train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
rbf_training_accuracy = rbf_clf.score(X_Train, Y_Train) #Compute the mean accuracy for training data
rbf_testing_accuracy = rbf_clf.score(X_Test, Y_Test) # Compute the mean accuracy for testing data
print(rbf_training_accuracy)
print(rbf_testing_accuracy)
      
#Accuracy for training data is approzimately the same as that of linear
# Accuracy for testing data is much lower than all previous models. 

0.9733333333333334
0.9333333333333333


In [31]:
# Let's look into the accuracy per classification (Instead of total/overall)
# We will look at the accuracy between the Testing data!

rbf_Y_Predict = rbf_clf.predict(X_Test)
print(rbf_Y_Predict)

[2. 1. 0. 2. 0. 2. 0. 1. 1. 1. 2. 1. 1. 1. 1. 0. 1. 1. 0. 0. 2. 1. 0. 0.
 1. 0. 0. 1. 1. 0. 2. 1. 0. 2. 2. 1. 0. 2. 1. 1. 2. 0. 2. 0. 0. 1. 2. 2.
 1. 2. 1. 2. 1. 1. 2. 1. 1. 2. 1. 2. 1. 0. 2. 1. 1. 1. 1. 2. 0. 0. 2. 1.
 0. 0. 1.]


In [32]:
#Import scikit-learn metrics module for accuracy calculation\n",
from sklearn import metrics

# Confirm score is the same as above for testing data (As it should be)
print("Accuracy:",metrics.accuracy_score(Y_Test, rbf_Y_Predict))
# It is. 

Accuracy: 0.9333333333333333


In [33]:
from sklearn.metrics import classification_report
print(classification_report(Y_Test, rbf_Y_Predict))

#Focusing on just precision, we can see that setosa is the most correctly classified, then versicolor, then viriginica. 
#With a decrease in precision

#While this model is different from Adeline, remmeber that we had the mos taccuracy there, 
#for setosa becasue it was more defined/seperated by its features. 
#Having lower sepall widht/length sepal values.




             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00        21
        1.0       0.88      0.97      0.92        30
        2.0       0.95      0.83      0.89        24

avg / total       0.94      0.93      0.93        75



In [34]:
# Notice how here we see the least accuracy for the classification label of 1.0
# and a decrease of 2.0 and overall score


# What's the explanation for this. Well from my brief understanding of RBF is that it tries to group them more alined than just by a line.
#However if we recall from the iris dataset, many points of Versicolor + Virginica cross over, so the model may be overfitting too much
#and thus decreasing the margin/space. 

In [35]:
linearSVC_clf = svm.LinearSVC(C=1.0, max_iter=10000)

In [36]:
linearSVC_clf.fit(X_Train, Y_Train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=10000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [37]:
linearSVC_training_accuracy = linearSVC_clf.score(X_Train, Y_Train) #Compute the mean accuracy for training data
linearSVC_testing_accuracy = linearSVC_clf.score(X_Test, Y_Test) # Compute the mean accuracy for testing data
print(linearSVC_training_accuracy)
print(linearSVC_testing_accuracy)
      
#Accuracy for training data is approzimately the same as that of linear
# Accuracy for testing data is much lower than all previous models. 

0.9733333333333334
0.92


In [38]:
# Let's look into the accuracy per classification (Instead of total/overall)
# We will look at the accuracy between the Testing data!

linearSVC_Y_Predict = linearSVC_clf.predict(X_Test)
print(linearSVC_Y_Predict)

[2. 1. 0. 2. 0. 2. 0. 1. 1. 1. 2. 1. 1. 1. 1. 0. 1. 1. 0. 0. 2. 2. 0. 0.
 2. 0. 0. 1. 1. 0. 2. 2. 0. 2. 2. 1. 0. 2. 1. 1. 2. 0. 2. 0. 0. 1. 2. 2.
 1. 2. 1. 2. 2. 1. 2. 2. 2. 2. 1. 2. 2. 0. 2. 1. 1. 1. 1. 2. 0. 0. 2. 1.
 0. 0. 1.]


In [39]:
#Import scikit-learn metrics module for accuracy calculation\n",
from sklearn import metrics

# Confirm score is the same as above for testing data (As it should be)
print("Accuracy:",metrics.accuracy_score(Y_Test, linearSVC_Y_Predict))
# It is. 

Accuracy: 0.92


In [40]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_Test, linearSVC_Y_Predict))
#Focusing on just precision, we can see that setosa is the most correctly classified, then versicolor, then viriginica. 
#With a decrease in precision

#While this model is different from Adeline, remmeber that we had the mos taccuracy there, 
#for setosa becasue it was more defined/seperated by its features. 
#Having lower sepall widht/length sepal values.





             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00        21
        1.0       0.96      0.83      0.89        30
        2.0       0.82      0.96      0.88        24

avg / total       0.93      0.92      0.92        75



In [41]:
print("Accuracy Linear:",metrics.accuracy_score(Y_Test, linear_Y_Predict))
print("Accuracy Poly:",metrics.accuracy_score(Y_Test, polynomial_Y_Predict))
print("Accuracy RBF:",metrics.accuracy_score(Y_Test, rbf_Y_Predict))
print("Accuracy AdjustesdLinear:",metrics.accuracy_score(Y_Test, linearSVC_Y_Predict))

Accuracy Linear: 0.9733333333333334
Accuracy Poly: 0.9733333333333334
Accuracy RBF: 0.9333333333333333
Accuracy AdjustesdLinear: 0.92


In [ ]:
To summerize my results.

For this assignment, we had to model Support Vector Classifiers with different kernels.
The dataset that we used is the iris dataset.
From previous assingments + discussions, one thing that we know is that the iris dataset is not linearly seperable 
(As we saw in the plots.) 
The Iris dataset has 3 classifications Setosa, Versicolor, and Viriginica, 
and four features: Sepal Lenght, Sepal Width, Petal Lenght, Petal Width.
    
For the Support Vector Classifiers we passed in all 3 classification and 4 features.
The data used was first split into 50 percent training data and 50 percent testing data. 
(Value is chosen to be consistent with previous assingments)

The four Kernels that were modeled are linear, polynomial, radial or rbf, and linear which minimizes the squared hinge loss and uses OVA instead of OAO reduction.

As initial hypothesis was that Polynomial and RBF kernels are to produce more accurate models, as they
are intended to work for non-linearly seperatable data. 
The polynomial kernal seeks a mapping function of degree 3 (The number of features - 1)
and the RBF seeks to group regions, or informally the neighbors around it and group them.
The linear kernels, of course seek to find lines that divide the three classes. 


After running the four models, we notice that Polynomial indeed has the greatest accuracy, of 0.97 on the test data.
After that, follows the ordinary linear of 0.97.
To our surprise, rbf (which is the most commonly used kernel) had a low accuracy of 0.93. 
Finally, 'adjusted' linear has the lowest accuracy of 0.92.

If we observe the score on the training data (found in the preceeding cells)
we will notice that the order from greatest to least acuracy on the training 
data follows polynomial, linear, rbf, and adjusted linear.

Thus, the Support vector classifier model that best fits the iris dataset 
is the one with a Polynomial Kernal.  
